# Generated by Django 2.1.1 on 2018-09-24 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('handy_helper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
